### PR TITLE
Always output 0 as the first bit of a DR bypass scan, per the 1149.1 …

### PR DESCRIPTION
**Pull request by elindberg-ghs**
…spec.

### CODE REVIEW

**Comment by agrobman** [comment]
thanks for finding this problem, it will be fixed in next release

**Comment by agrobman** [comment]
BTW, how did you find the problem?

**Comment by elindberg-ghs** [comment]
Another engineer hit validation issues when testing the SweRV FPGA implementation in hardware using our debug probe. I noticed that the first bit output from the DR bypass register was dependent on the last shift, and easily tracked it down to the HDL.

IR scan (5 bit) 0x1f  (bypass instruction)
DR scan (32 bit) 0x0 -- returns 0x00000001  (incorrect)

IR scan (5 bit) 0x00  (treated as another bypass instruction)
DR scan (32 bit) 0x0 -- returns 0x00000000  (correct)

This is contrary to the 1149.1-2001 spec, section 10.1.1 (b), which says "When the bypass register is selected for inclusion in the serial path between TDI and TDO by the current instruction, the shift-register stage shall bet set to a logic zero on the rising edge of TCK after entry into the Capture-DR controller state."

It's a pretty minor issue, really, but it can impact things like target detection with multiple devices on the JTAG chain.

**Comment by agrobman** [comment]
Did this issue effect external tools you are using ( debuggers etc ...) except he case you mentioned? 
BTW, what kind of check was failing ? Theoretically if the JTAG in BYPASS, JTAG driver should shift one clock more  to read/write chained Data register of the 2nd JTAG module and ignore bit value from the bypass register ...

**Comment by elindberg-ghs** [comment]
Right -- the bit is normally ignored, and doesn't impact debugging the CPU. But we have a few low-level checks that expect it to be zero.

**Comment by agrobman** [comment]
Just curious, where these low level checks from? Are they from some JTAG verification tool?

**Comment by elindberg-ghs** [comment]
Just some in-house checks for our product.

**Comment by agrobman** [comment]
thanks for update

**Comment by aprnath** [comment]
This will fixed and updated in the next release. Thank you for reporting the issue.

**Pull request closed without merging**
